_default:
  @just --choose

[doc("Install module & dependencies")]
install-dev:
    pip install -e ".[dev]"

[doc("Run Jupyter Server Locally")]
run-notebook:
    jupyter lab

[doc("Check Syntax (RUFF)")]
syntax-check:
    ruff check

[doc("Check Typing (mypy)")]
type-check:
    mypy src/

[doc("Install extra-types")]
types-install:
    mypy --install-types

[doc("Auto Formatting (RUFF)")]
format:
    ruff format src/

[doc("Commit and push all changes")]
commit-push message="":
    git commit {{ if message != "" { "-m " + message } else {""} }}
    git push

[doc("Update git remote")]
update-remote url:
    git remote set-url origin {{url}}
